troops:
  - commander: cxxx0
    place: S101
    subordinates:
      - lxxx0
      - lxxx1
      - b8:27:eb:ff:39:fc
      - b8:27:eb:0e:09:08
  - commander: cxxx1
    place: S103
    subordinates:
      - lxxx2
      - lxxx3
      - lxxx4
squads:
  - leader: b8:27:eb:ff:39:fc
    place: desk-wall
    subordinates:
      - soldier: CC2650-a0:e6:f8:b6:f4:02
        place: whiteboard
  - leader: b8:27:eb:0e:09:08
    place: desk0
    subordinates:
      - soldier: CC2650-a0:e6:f8:ae:ad:82
        place: right1
      - soldier: CC2650-a0:e6:f8:c1:a6:00
        place: right2
  - leader: lxxx0
    place: desk1
    subordinates:
      - soldier: sxxx0
        place: left
      - soldier: sxxx1
        place: right
      - soldier: CC2650-a0:e6:f8:ae:ad:82
        place: window
      - soldier: CC2650-a0:e6:f8:c1:a6:00
        place: onPC
  - leader: lxxx1
    place: desk1
    subordinates:
      - soldier: sxxx2
        place: left
      - soldier: sxxx3
        place: right
  - leader: lxxx2
    place: desk2
    subordinates:
      - soldier: sxxx4
        place: left
      - soldier: sxxx5
        place: right
  - leader: lxxx3
    place: desk3
    subordinates:
      - soldier: sxxx6
        place: left
      - soldier: sxxx7
        place: right
  - leader: lxxx4
    place: desk4
    subordinates:
      - soldier: sxxx8
        place: right

