troops:
  - commander: cxxx0
    subordinates:
      - lxxx0
      - lxxx1
      - lxxx2
  - commander: cxxx1
    subordinates:
      - lxxx3
      - lxxx4
      - lxxx5
squads:
  - leader: lxxx0
    subordinates:
      - sxxx0
      - sxxx1
      - CC2650-a0:e6:f8:ae:ad:82
      - CC2650-a0:e6:f8:c1:a6:00
  - leader: lxxx1
    subordinates:
      - sxxx2
      - sxxx3
  - leader: lxxx2
    subordinates:
      - sxxx4
      - sxxx5
  - leader: lxxx3
    subordinates:
      - sxxx6
      - sxxx7
  - leader: lxxx4
    subordinates:
      - sxxx8
  - leader: lxxx5
    subordinates:
      - sxxx9
      - sxx10
      - sxx11
